/* The typographic shapes a value is written in (layer 1 of docs/QUALITY-PLAN.md).
   Shared by tests/shapes_t.js, which checks each shape, and scripts/harvest-shapes.js,
   which checks that every shape seen in a real document is one of these (layer 4). */
const SHAPES = {
  plain: (x) => `המורה ${x} אמרה.`,
  "double quotes": (x) => `המורה "${x}" אמרה.`,
  "prefix + double quotes": (x) => `נפגשתי ב"${x}" אתמול.`,
  "single quotes": (x) => `המורה '${x}' אמרה.`,
  "typographic quotes": (x) => `המורה “${x}” אמרה.`,
  "reversed typographic quotes": (x) => `המורה ”${x}“ אמרה.`,
  "Hebrew gershayim as quotes": (x) => `המורה ״${x}״ אמרה.`,
  "low-high quotes": (x) => `המורה „${x}” אמרה.`,
  guillemets: (x) => `המורה «${x}» אמרה.`,
  parentheses: (x) => `המורה (${x}) אמרה.`,
  brackets: (x) => `המורה [${x}] אמרה.`,
  commas: (x) => `המורה, ${x}, אמרה.`,
  "speaker colon": (x) => `${x}: אני מסכימה.`,
  "en dashes": (x) => `המורה – ${x} – אמרה.`,
  "maqaf join": (x) => `המורה־${x} אמרה.`,
  slash: (x) => `המורה/${x} אמרה.`,
  "no-break space inside": (x) => `המורה ${x.replace(" ", " ")} אמרה.`,
  "RLM around": (x) => `המורה ‏${x}‏ אמרה.`,
  "LRM inside": (x) => `המורה ${x.replace(" ", " ‎")} אמרה.`,
  "line break inside": (x) => `המורה ${x.replace(" ", "\n")} אמרה.`,
  "tab inside": (x) => `המורה ${x.replace(" ", "\t")} אמרה.`,
  "double space inside": (x) => `המורה ${x.replace(" ", "  ")} אמרה.`,
  ellipsis: (x) => `המורה…${x}… אמרה.`,
  "question mark": (x) => `האם ${x}? כן.`,
  bullet: (x) => `• ${x}`,
  numbered: (x) => `1. ${x} הגישה.`,
  asterisks: (x) => `המורה *${x}* אמרה.`,
  underscores: (x) => `המורה _${x}_ אמרה.`,
  "footnote digit after": (x) => `המורה ${x}2 אמרה.`,
  // seen in her documents (layer 4): a right-to-left embedding mark before a name, and a
  // bracket straight after one
  "RLE and PDF around": (x) => `המורה ‫${x}‬ אמרה.`,
  "bracket straight after": (x) => `המורה ${x}[1] אמרה.`,
  "prefix ל": (x) => `כתבתי ל${x} אתמול.`,
  "prefix ב": (x) => `נפגשתי ב${x} אתמול.`,
  "prefix ו": (x) => `אני ו${x} הגענו.`,
  "prefix ש": (x) => `אמרתי ש${x} צודקת.`,
  "prefix מ": (x) => `שמעתי מ${x} אתמול.`,
  "prefix כ": (x) => `היא כמו כ${x} אתמול.`,
  "prefix ה": (x) => `ראיתי ה${x} אתמול.`,
  "prefix כש": (x) => `אמרתי כש${x} הגיעה.`,
  "prefix ול": (x) => `כתבתי לו ול${x} אתמול.`,
  "prefix וב": (x) => `ראיתי אותו וב${x} אתמול.`,
  "footnote digit before": (x) => `המורה 2${x} אמרה.`,
};

module.exports = { SHAPES };
