/* The hosted build's changes to the tool's page (app/index.html). The public GitHub Pages tool is
   built without any of this.
   1. It signs in: the page also loads the sign-in client, the project's config and cloud.js (from
      the site root, one level up), and may talk to the Supabase project.
   2. It asks no other site for anything. The tool loads React, ReactDOM and Babel from unpkg, d3
      and topojson from unpkg, the world map's data and the AI runtime's WebAssembly from jsdelivr,
      and its fonts from Google Fonts: each of those sees the visitor's address. Here the site
      serves them itself: the same package releases, checked byte for byte by the build against
      the hashes the tool already pins (scripts/build-hosted.js), handed to the tool through
      window.__resources (hosted-resources.js) or by address in the page, and the page's
      Content-Security-Policy names no other site but the project.
   e2e/cloud.spec.js and e2e/hosted-build.spec.js run the page this produces. */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const read = (f) => fs.readFileSync(path.join(ROOT, f), "utf8");
const pkgVersion = (name) => JSON.parse(read(path.join("node_modules", name, "package.json"))).version;
const supabaseVersion = () => pkgVersion("@supabase/supabase-js");
const PROJECT = (read("site/config.js").match(/url: "(https:\/\/[a-z0-9]+\.supabase\.co)"/) || [])[1];
const ORT_V = (read("redact-engine.js").match(/const ORT_V="([^"]+)"/) || [])[1];

/* The libraries the tool takes from other sites, and where the hosted site keeps its own copy.
   pin: where the tool's own hash for that file is (a Subresource Integrity sha384, or the engine's
   SHA-256 for the runtime), so the build can refuse a copy that is not the same file. */
const LIBS = [
  { url: "https://unpkg.com/react@18.3.1/umd/react.production.min.js", from: "node_modules/react/umd/react.production.min.js", to: "vendor/react-18.3.1.production.min.js", via: "resources",
    pin: () => (read("support.js").match(/REACT_SRI = "(sha384-[^"]+)"/) || [])[1] },
  { url: "https://unpkg.com/react-dom@18.3.1/umd/react-dom.production.min.js", from: "node_modules/react-dom/umd/react-dom.production.min.js", to: "vendor/react-dom-18.3.1.production.min.js", via: "resources",
    pin: () => (read("support.js").match(/REACT_DOM_SRI = "(sha384-[^"]+)"/) || [])[1] },
  { url: "https://unpkg.com/@babel/standalone@7.29.0/babel.min.js", from: "node_modules/@babel/standalone/babel.min.js", to: "vendor/babel-standalone-7.29.0.min.js", via: "resources",
    pin: () => (read("support.js").match(/BABEL_SRI = "(sha384-[^"]+)"/) || [])[1] },
  { url: "https://unpkg.com/d3@7.9.0/dist/d3.min.js", from: "node_modules/d3/dist/d3.min.js", to: "vendor/d3-7.9.0.min.js", via: "page",
    pin: () => (read("index.html").match(/d3@7\.9\.0\/dist\/d3\.min\.js","(sha384-[^"]+)"/) || [])[1] },
  { url: "https://unpkg.com/topojson-client@3.1.0/dist/topojson-client.min.js", from: "node_modules/topojson-client/dist/topojson-client.min.js", to: "vendor/topojson-client-3.1.0.min.js", via: "page",
    pin: () => (read("index.html").match(/topojson-client@3\.1\.0\/dist\/topojson-client\.min\.js","(sha384-[^"]+)"/) || [])[1] },
  // data, not code: the page fetches it without a pinned hash, as from the CDN
  { url: "https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-110m.json", from: "node_modules/world-atlas/countries-110m.json", to: "vendor/world-atlas-2.0.2/countries-110m.json", via: "atlas", pin: () => null },
];
// the runtime's WebAssembly, at the version transformers.js runs (an npm alias pins it); the engine
// joins parts and checks the SHA-256 it pins (window.__resources.ort)
const ORT_FILES = ["ort-wasm-simd-threaded.asyncify", "ort-wasm-simd-threaded"];
const ortFrom = (name) => "node_modules/onnxruntime-web-1.24/dist/" + name + ".wasm";
const ortPin = (name) => (read("redact-engine.js").match(new RegExp('"' + name.replace(/\./g, "\\.") + '":"([^"]+)"')) || [])[1];
const ORT_DIR = () => "vendor/ort-" + ORT_V + "/";

// the fonts the tool takes from Google Fonts, from the same families' npm releases (OFL)
const FONTS = [["rubik", [300, 400, 500, 600]], ["noto-serif-hebrew", [400, 500]]];
const FONT_SUBSETS = /\/\* [a-z-]+-(?:hebrew|latin|latin-ext)-\d+-normal \*\//;

// window.__resources for the hosted page: support.js loads React, ReactDOM and Babel from here,
// the atlas its data, and the engine the runtime's WebAssembly (parts: name -> how many)
function resourcesScript(ortParts) {
  const map = {};
  for (const l of LIBS) if (l.via === "resources") map[l.url] = "./" + l.to;
  map.atlas = "./" + LIBS.find((l) => l.via === "atlas").to;
  map.ort = { base: "./" + ORT_DIR(), parts: ortParts || {} };
  return "/* Generated by scripts/build-hosted.js: the hosted site serves the tool's libraries itself. */\n" +
    "window.__resources = Object.assign(window.__resources || {}, " + JSON.stringify(map, null, 1) + ");\n";
}

const FONT_LINKS = /<link rel="preconnect" href="https:\/\/fonts\.googleapis\.com">\s*<link rel="preconnect" href="https:\/\/fonts\.gstatic\.com" crossorigin>\s*<link href="https:\/\/fonts\.googleapis\.com\/css2\?[^"]+" rel="stylesheet">/g;
const THIRD = /https:\/\/(?:unpkg\.com|cdn\.jsdelivr\.net|fonts\.googleapis\.com|fonts\.gstatic\.com)/;

function hostedApp(html) {
  if (!PROJECT) throw new Error("hosted: no project URL in site/config.js");
  const anchor = '<script src="./page-logic.js"></script>';
  const cspRe = /(<meta http-equiv="Content-Security-Policy" content=")([^"]*)(")/;
  if (!html.includes(anchor) || !cspRe.test(html)) throw new Error("hosted: app/index.html no longer has the places this inserts into");
  let out = html;
  // the policy: no other site, and the project for connections
  out = out.replace(cspRe, (_, a, csp, z) => a + csp.split(";").map((d) => d.trim().split(/\s+/).filter((t) => !THIRD.test(t)).join(" "))
    .map((d) => (/^connect-src\b/.test(d) ? d + " " + PROJECT : d)).join("; ") + z);
  // the fonts: the site's own files instead of Google Fonts (in the page's head, and in the template's)
  const fontLinks = (out.match(FONT_LINKS) || []).length;
  if (!fontLinks) throw new Error("hosted: the Google Fonts links are not where they were");
  out = out.replace(FONT_LINKS, '<link href="./fonts/app-fonts.css" rel="stylesheet">');
  // the map's libraries and data, by address in the page (the data also through __resources);
  // the libraries' integrity attributes stay and still apply
  for (const l of LIBS.filter((x) => x.via === "page" || x.via === "atlas")) {
    if (!out.includes(l.url)) throw new Error("hosted: the page no longer loads " + l.url);
    out = out.split(l.url).join("./" + l.to);
  }
  out = out.replace(anchor, `<script src="./hosted-resources.js"></script>\n<script src="../vendor/supabase-${supabaseVersion()}.js"></script>\n<script src="../config.js"></script>\n<script src="../cloud.js"></script>\n` + anchor);
  const left = out.match(new RegExp(THIRD.source + "[^\"'\\s)]*"));
  if (left) throw new Error("hosted: app/index.html still names another site: " + left[0]);
  return out;
}

module.exports = { hostedApp, resourcesScript, PROJECT, LIBS, ORT_FILES, ORT_V, ortFrom, ortPin, ORT_DIR, FONTS, FONT_SUBSETS };
